"""initial tables

Revision ID: b4a6d2f27f83
Revises: 
Create Date: 2026-05-04 13:47:01.697489
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a6d2f27f83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_user', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('provider_call_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('segment_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('model_code', sa.String(length=64), nullable=False),
    sa.Column('request_summary', sa.Text(), nullable=True),
    sa.Column('response_summary', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('provider_error_code', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_call_logs_model_code_created_at', 'provider_call_logs', ['model_code', 'created_at'], unique=False)
    op.create_index('ix_provider_call_logs_task_id', 'provider_call_logs', ['task_id'], unique=False)
    op.create_table('tts_task_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('segment_no', sa.Integer(), nullable=False),
    sa.Column('segment_text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_task_id', sa.String(length=128), nullable=True),
    sa.Column('audio_url', sa.String(length=1024), nullable=True),
    sa.Column('audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tts_task_segments_task_id_segment_no', 'tts_task_segments', ['task_id', 'segment_no'], unique=False)
    op.create_table('tts_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_no', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_code', sa.String(length=64), nullable=False),
    sa.Column('final_model_code', sa.String(length=64), nullable=True),
    sa.Column('fallback_used', sa.Integer(), nullable=False),
    sa.Column('voice_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('text_char_count', sa.Integer(), nullable=False),
    sa.Column('style_prompt', sa.String(length=1000), nullable=True),
    sa.Column('speed', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('pitch', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('volume', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('emotion', sa.String(length=64), nullable=True),
    sa.Column('output_format', sa.String(length=16), nullable=False),
    sa.Column('audio_url', sa.String(length=1024), nullable=True),
    sa.Column('audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('provider_task_id', sa.String(length=128), nullable=True),
    sa.Column('provider_error_code', sa.String(length=64), nullable=True),
    sa.Column('provider_error_message', sa.String(length=1000), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('ix_tts_tasks_model_code_created_at', 'tts_tasks', ['model_code', 'created_at'], unique=False)
    op.create_index('ix_tts_tasks_status_created_at', 'tts_tasks', ['status', 'created_at'], unique=False)
    op.create_index('ix_tts_tasks_user_id_created_at', 'tts_tasks', ['user_id', 'created_at'], unique=False)
    op.create_table('usage_stats_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('model_code', sa.String(length=64), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('fallback_count', sa.Integer(), nullable=False),
    sa.Column('text_char_count', sa.BigInteger(), nullable=False),
    sa.Column('audio_duration_ms', sa.BigInteger(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('voice_clone_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voice_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source_audio_url', sa.String(length=1024), nullable=False),
    sa.Column('source_audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('consent_type', sa.String(length=32), nullable=False),
    sa.Column('consent_statement', sa.String(length=2000), nullable=False),
    sa.Column('consent_proof_url', sa.String(length=1024), nullable=True),
    sa.Column('risk_status', sa.String(length=32), nullable=False),
    sa.Column('review_note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('profile_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_code', sa.String(length=64), nullable=False),
    sa.Column('provider_voice_id', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('gender_hint', sa.String(length=32), nullable=True),
    sa.Column('age_hint', sa.String(length=32), nullable=True),
    sa.Column('language_hint', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_public', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voice_profiles_provider_voice_id', 'voice_profiles', ['provider_voice_id'], unique=False)
    op.create_index('ix_voice_profiles_user_id_profile_type', 'voice_profiles', ['user_id', 'profile_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_voice_profiles_user_id_profile_type', table_name='voice_profiles')
    op.drop_index('ix_voice_profiles_provider_voice_id', table_name='voice_profiles')
    op.drop_table('voice_profiles')
    op.drop_table('voice_clone_sources')
    op.drop_table('users')
    op.drop_table('usage_stats_daily')
    op.drop_index('ix_tts_tasks_user_id_created_at', table_name='tts_tasks')
    op.drop_index('ix_tts_tasks_status_created_at', table_name='tts_tasks')
    op.drop_index('ix_tts_tasks_model_code_created_at', table_name='tts_tasks')
    op.drop_table('tts_tasks')
    op.drop_index('ix_tts_task_segments_task_id_segment_no', table_name='tts_task_segments')
    op.drop_table('tts_task_segments')
    op.drop_index('ix_provider_call_logs_task_id', table_name='provider_call_logs')
    op.drop_index('ix_provider_call_logs_model_code_created_at', table_name='provider_call_logs')
    op.drop_table('provider_call_logs')
    op.drop_index('ix_audit_logs_user', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
